import js from "@eslint/js";
import globals from "globals";
import { defineConfig, globalIgnores } from "eslint/config";

// ESLint configuration for the whole project.
// The rules below are our team's JavaScript conventions — the ones a tool can
// check. The full conventions, with examples and the reasoning behind them,
// live in docs/tutorials/javascript.md.
export default defineConfig([
  // dist/ is generated by `npm run build`. Never edited by hand, so never linted.
  globalIgnores(["dist/", ".wrangler/"]),

  // ESLint's own recommended set: real mistakes, not style.
  // Typos (no-undef), leftovers (no-unused-vars), code that can never run.
  js.configs.recommended,

  // Tells ESLint which globals exist without being declared, so it does not
  // report `document`, `window`, `fetch` or `console` as undefined.
  {
    languageOptions: {
      globals: globals.browser,
    },
  },

  // Our team rules, for every .js file in the repo (config files included).
  {
    rules: {
      // `var` has confusing scoping rules. Use const/let.
      "no-var": "error",
      // A variable that is never reassigned should say so. Auto-fixable.
      "prefer-const": "error",
      // `==` converts types behind your back ("2" == 2 is true). Always `===`.
      eqeqeq: ["error", "always"],
      // camelCase names. `properties: "never"` lets us read API fields as they
      // come (monster.hit_points) without renaming the API's data.
      camelcase: ["error", { properties: "never" }],
      // Debug logs should not reach main — a warning, so CI still passes while
      // you work. console.warn/console.error are real output and stay allowed.
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },

  // Two extra rules for our own game code only, not for config files.
  {
    files: ["src/**/*.js"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "ExportDefaultDeclaration",
          message:
            "Use named exports (export function ...), not export default.",
        },
        {
          selector: "AssignmentExpression[left.property.name='innerHTML']",
          message:
            "Don't assign innerHTML. Use textContent, or build elements with createElement. Quiz questions contain HTML code.",
        },
      ],
    },
  },
]);
